### ISSUE TITLE
Depends on Node v16 but GitHub requires at least Node v20

### ISSUE THREAD

**Issue by hasko** [JorelAli/setup-elm#11]
When I created a new workflow with this action, GitHub complained that it uses Node v16 and refused to run. Apparently, it must use at least Node v20.

**Comment by LinusSee** [comment]
Hey @JorelAli, just a reminder so the issue isn't forgotten. Hoping you have the time to look over and merge the PR
Also thank you for writing an elm-action in the first place 😄
